[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/server"
  status = 200

[dev]
  command = "npm run dev"
  port = 5000